apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
spec:
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      containers:
        - env:
            - name: PORT
              value: '8080'
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: 'productcatalogservice:3550'
          image: recommendationservice
          livenessProbe:
            exec:
              command:
                - /bin/grpc_health_probe
                - '-addr=:8080'
            periodSeconds: 5
          name: server
          ports:
            - containerPort: 8080
          readinessProbe:
            exec:
              command:
                - /bin/grpc_health_probe
                - '-addr=:8080'
            periodSeconds: 5
          resources:
            limits:
              cpu: 200m
              memory: 450Mi
            requests:
              cpu: 100m
              memory: 220Mi
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
spec:
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
  selector:
    app: recommendationservice
  type: ClusterIP
